### PR TITLE
New drill icon in the legacy renderer.

### PR DESCRIPTION
**Pull request by srschandan**
VS Code light:
Screenshot 2023-12-06 at 1 52 54 PM

VS Code dark:
Screenshot 2023-12-06 at 1 53 13 PM

### CODE REVIEW

**Comment by srschandan** [comment]
> I wonder if it would be good to have this externally configurable, since the action defined by drilling is configurable and won't likely be copy in the long run.

Agree. This was supposed to go into the new renderer but that the design and functionality is not finalized yet. This is more like get a better icon in there right now to make it look better.

**Review by skokenes — CHANGES_REQUESTED** [review]
Code looks good, but this implementation causes the text in the table cells to no longer be vertically centered. Can you fix that?

**Comment by srschandan** [comment]
> Code looks good, but this implementation causes the text in the table cells to no longer be vertically centered. Can you fix that?

Our cell contents are always aligned to top. https://github.com/malloydata/malloy/blob/49c4b9b69ef557358d2a4653e3b8658abc112796/packages/malloy-render/src/html/table.ts#L417

I reduced the padding on the drill icon to make sure when there's only one line of data in the table, everything looks center aligned.

**Comment by skokenes** [comment]
It's weird, on multiline cells in VS Code extension it looks aligned with top line:
CleanShot 2023-12-08 at 09 39 03@2x

But on single line rows, it looks slightly off:
CleanShot 2023-12-08 at 09 40 14@2x

I don't think this really matters for now; we don't do solid control over the row height, font size etc in the old renderer so that will make it difficult to have it aligned properly to the first line in every situation.

This looks good to me

**Pull request merged**
