### PR TITLE
Multilevel docs sidebar (and add Postgres example)

### PR DESCRIPTION
**Pull request by danesolberg**
PR discussed with @anikaks about adding a Postgres example into the documentation (#615).

I wanted to group this new example in the docs sidebar alongside the BQ version that it modifies, so I also included a **change to the sidebar logic** to allow for section nesting.  Previously you couldn't put an expanding section within a section.

postgres

### CODE REVIEW

**Comment by anikaks** [comment]
The docs changes LGTM, @christopherswenson can you take a look at the sidebar change?

**Comment by christopherswenson** [comment]
Hey, thanks for your contribution @danesolberg. I'll try to take a look at this either later today or early next week.

**Review by christopherswenson — APPROVED** [review]
This looks great to me! Once I confirm the contribution guidelines I think we can merge this.

**Pull request merged**
